In [1]:
import numpy as np
import numpy.ma as ma
from numba import njit
import matplotlib.pyplot as plt
from IPython.display import display

# 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.arange(10)
arr.flags.writeable = False
arr[0] = 2

ValueError: assignment destination is read-only

## 1.1

Чем отличается C_CONTIGUOUS от F_CONTIGUOUS

In [7]:
arr = np.arange(10)
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [8]:
arr = arr.reshape((2,5))
print(arr)
print(arr.flags)

[[0 1 2 3 4]
 [5 6 7 8 9]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [9]:
arr = arr.T
print(arr)
print(arr.flags)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [10]:
arr = arr[:, ::-1]
print(arr)
print(arr.flags)

[[5 0]
 [6 1]
 [7 2]
 [8 3]
 [9 4]]
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



# 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [236]:
arr_lin = np.linspace(start=-5, stop=5, num=10)
arr_lin

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [237]:
arr_lin2 = np.linspace(start=-5, stop=5, num=10)
arr_lin2

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [241]:
meshgrid_ij = np.meshgrid(arr_lin, arr_lin2, indexing='ij', sparse=True)
x, y = meshgrid_ij
print(x.shape, y.shape)

(10, 1) (1, 10)


In [242]:
def f(x, y):
    return x**2 + y**2

In [243]:
f(x, y)

array([[50.        , 40.12345679, 32.71604938, 27.77777778, 25.30864198,
        25.30864198, 27.77777778, 32.71604938, 40.12345679, 50.        ],
       [40.12345679, 30.24691358, 22.83950617, 17.90123457, 15.43209877,
        15.43209877, 17.90123457, 22.83950617, 30.24691358, 40.12345679],
       [32.71604938, 22.83950617, 15.43209877, 10.49382716,  8.02469136,
         8.02469136, 10.49382716, 15.43209877, 22.83950617, 32.71604938],
       [27.77777778, 17.90123457, 10.49382716,  5.55555556,  3.08641975,
         3.08641975,  5.55555556, 10.49382716, 17.90123457, 27.77777778],
       [25.30864198, 15.43209877,  8.02469136,  3.08641975,  0.61728395,
         0.61728395,  3.08641975,  8.02469136, 15.43209877, 25.30864198],
       [25.30864198, 15.43209877,  8.02469136,  3.08641975,  0.61728395,
         0.61728395,  3.08641975,  8.02469136, 15.43209877, 25.30864198],
       [27.77777778, 17.90123457, 10.49382716,  5.55555556,  3.08641975,
         3.08641975,  5.55555556, 10.49382716

In [25]:
meshgrid_xy = np.meshgrid(arr_log, arr_lin, arr_lin2, indexing='xy')
x, y, z = meshgrid_xy
print(x.shape, y.shape, z.shape)

(6, 5, 10) (6, 5, 10) (6, 5, 10)


In [28]:
meshgrid_xy = np.meshgrid(arr_log, arr_lin, arr_lin2, indexing='xy', sparse=True)
x, y, z = meshgrid_xy
print(x.shape, y.shape, z.shape)
print(x)
print(y)
print(z)

(1, 5, 1) (6, 1, 1) (1, 1, 10)
[[[ 10.        ]
  [ 17.7827941 ]
  [ 31.6227766 ]
  [ 56.23413252]
  [100.        ]]]
[[[0.        ]]

 [[1.25663706]]

 [[2.51327412]]

 [[3.76991118]]

 [[5.02654825]]

 [[6.28318531]]]
[[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111
    0.11111111  0.33333333  0.55555556  0.77777778  1.        ]]]


# 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [23]:
arr = np.diag(np.arange(1, 5), k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 4

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [322]:
def gen(n):
    for i in range(n + 1):
        yield i

In [327]:
%%timeit
arr1 = np.fromiter(gen(100), dtype=np.int32, count=101)

6.54 µs ± 9.08 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [328]:
%%timeit
arr2 = np.array([i for i in gen(100)], dtype=np.int32)

10.1 µs ± 21.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# 5

Что будет выведено на экран? 
```
a = np.arange(4).reshape(2,2)
a += 0.5
print(a)
```

In [55]:
a = np.arange(4).reshape(2,2) # без dtype=np.float64 кинет ошибку, потому что разные типы
a += 0.5 # inplace operation
print(a)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [65]:
a = np.arange(4).reshape(2,2) # без dtype=np.float64 кинет ошибку, потому что разные типы
a = a + 0.5
print(a)

[[0.5 1.5]
 [2.5 3.5]]


In [66]:
a = np.arange(4).reshape(2,2)
a.__iadd__(0.5)
print(a)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

# 6

Что будет выведено на экран?
```
a = np.array([1])
if a:
    print("True")
else:
    print("False")
a = np.array([1, 2, 3])
if a:
    print("True")
else:
    print("False")
```

In [57]:
a = np.array([1, 2, 3])
bool(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
print(bool(np.array([1])))
print(bool(np.array([0])))
print(bool(np.array([])))

True
False
False


/tmp/ipykernel_1467099/2309888753.py:3: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  print(bool(np.array([])))


# 7

"Что будет выведено на экран?
```
print(0 * np.nan)
print(np.nan - np.nan)
print(np.nan == np.nan)
print(np.nan is np.nan)
print(-np.inf < np.nan < np.inf)
```

In [208]:
print(0 * np.nan)
print(np.nan - np.nan)
print(np.nan == np.nan)
print(np.nan is np.nan)
print(-np.inf < np.nan < np.inf)

nan
nan
False
True
False


In [226]:
x = np.float32(0)/np.float32(0)
y = x
x == y

/tmp/ipykernel_1413596/3102600059.py:1: RuntimeWarning: invalid value encountered in scalar divide
  x = np.float32(0)/np.float32(0)


False

# 8

Что будет выведено на экран?
```
print(np.isnan(np.array([np.nan]).astype(np.int)))
```

In [107]:
np.isnan(np.array([np.nan]).astype(np.int32))

/tmp/ipykernel_1413596/3647518359.py:1: RuntimeWarning: invalid value encountered in cast
  np.isnan(np.array([np.nan]).astype(np.int32))


array([False])

# 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [100]:
n = 5
a = np.array([0,10,20,30])
a = np.repeat(a[:, np.newaxis], n, axis=1)
a += np.arange(n)
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [251]:
a = np.array([0,10,20,30])
a = a[:, np.newaxis]
a = a + np.arange(5)
print(a)

1 5 8 1
  2 5 1 
    
4 1
  5

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


# 10

Какой shape будет у результата операции 
```
np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?
```

In [104]:
a = np.arange(5).reshape(1,-1)
b = np.arange(5).reshape(-1,1)
a + b

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [118]:
a = np.arange(40).reshape(1, 5, 8, 1)
b = np.arange(10).reshape(2, 5, 1)
(a + b).shape
# broadcast не работает потому что мы идем справа налево в размерностях и в данном случае у нас такие размерности
# (1, 5, 8, 1)
#    (2, 5, 1)

ValueError: operands could not be broadcast together with shapes (1,5,8,1) (2,5,1) 

# 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [219]:
%%timeit
a = np.zeros((100,100))
a[0::2, 1::2] = 1
a[1::2, 0::2] = 1
a

4.88 µs ± 8.92 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [221]:

(np.arange(100)[:, np.newaxis] + np.arange(100)) % 2

array([[0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0]])

# 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [94]:
a = np.arange(1, 6)
b = np.zeros(2 * a.shape[0] - 1)
b[::2] = a
b

array([1., 0., 2., 0., 3., 0., 4., 0., 5.])

# 13

Что будет выведено на экран?
```
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])
```

In [253]:
a = np.arange(36).reshape((2,3,2,3))
print(a[..., 0, 0, 0, 0])
print(a[...,0,...])

0


IndexError: an index can only have a single ellipsis ('...')

# 14

Что будет выведено на экран?
```
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)
```

In [128]:
a = np.arange(16).reshape((4,4))
b = a[:,[2,3]]
b[:] = 0
print(np.shares_memory(a, b))
print(a)
b = a[:,2:]
b[:] = 0
print(np.shares_memory(a, b))
print(a)

False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
True
[[ 0  1  0  0]
 [ 4  5  0  0]
 [ 8  9  0  0]
 [12 13  0  0]]


In [257]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [260]:
a[(0,1,3),(1,2,0)]

array([ 1,  6, 12])

# 15

Замените отрицательные элементы массива нулем.

In [149]:
a = np.random.randint(-10, 10, size=10)
print(a)
np.where(a < 0, 0, a)

[ -7   7 -10   7  -6   8   8 -10   1   4]


array([0, 7, 0, 7, 0, 8, 8, 0, 1, 4])

In [207]:
a = np.random.randint(-10, 10, size=10)
print(a)
a[a < 0] = 0
print(a)

[ 6  9 -5 -1 -2  1  2 -3  4  8]
[6 9 0 0 0 1 2 0 4 8]


# 16

На примере целочисленного массива 
```
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
```
составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [90]:
a = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]])
print(a)
mask = (a[:,0,np.newaxis] == a).all(axis=1)
a[~mask]

[[1 2 3]
 [1 1 1]
 [2 2 1]
 [2 2 2]]


array([[1, 2, 3],
       [2, 2, 1]])

# 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [43]:
a = np.random.randint(0, 10, size=10)
print(a)
a_right = np.ones(10, dtype=bool)
a_left = np.ones(10, dtype=bool)

a_right[:-1] = a[:-1] <= a[1:]
a_left[1:] = a[:-1] >= a[1:]
print(a_right)
print(a_left)
print(a[(a_right & a_left)])

[1 0 2 1 0 8 4 1 5 4]
[False  True False False  True False False  True False  True]
[ True  True False  True  True False  True  True False  True]
[0 0 1 4]


In [200]:
a = np.random.randint(0, 10, size=10)
a

array([2, 3, 1, 5, 5, 7, 2, 0, 0, 7])

In [204]:
a_flag = np.ones(10, dtype=bool)

a_flag[:-1] = (a[:-1] - a[1:]) < 1
a_flag[1:] *= (a[1:] - a[:-1]) < 1
print(a[a_flag])

[2 1 5 0 0]


# 18

1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [315]:
a = np.random.randint(0, 10, size=9).reshape((3,3))
print(a)
print(a[:, 1].argsort())
a[a[:, 1].argsort()]

[[1 6 7]
 [7 9 9]
 [0 2 1]]
[2 0 1]


array([[0, 2, 1],
       [1, 6, 7],
       [7, 9, 9]])

## 18.1

отсортировать по нескольким столбцам

In [321]:
a = np.array([[2, 2, 2], 
              [2, 2, 1], 
              [2, 1, 2], 
              [2, 1, 1], 
              [1, 2, 2], 
              [1, 2, 1], 
              [1, 1, 2], 
              [1, 1, 1]])
print(a)
a.dtype = np.dtype([('0', int), ('1', int), ('2', int)])
print(a.dtype)
a.sort(order=['1', '2'], axis=0)

print(a.dtype)

[[2 2 2]
 [2 2 1]
 [2 1 2]
 [2 1 1]
 [1 2 2]
 [1 2 1]
 [1 1 2]
 [1 1 1]]
[('0', '<i8'), ('1', '<i8'), ('2', '<i8')]
[('0', '<i8'), ('1', '<i8'), ('2', '<i8')]


## 18.2

In [135]:
a = np.random.randint(0, 10, size=9).reshape((3,3))
print(a)
np.lexsort(a[:,[2,1]].T)

[[2 8 1]
 [6 8 9]
 [5 9 3]]


array([0, 1, 2])

# 19

Поменяйте местами первую и вторую строки двумерного массива

In [201]:
a = np.arange(0, 9).reshape((3,3))
a[[0,1], :] = a[[1,0], :]
print(a)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


# 20

1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [304]:
a = np.arange(0, 15).reshape((3,5))
print(a)
rows = np.array([[0], [2]])
cols = np.array([1, 3])
print(a[rows, cols])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  3]
 [11 13]]


# 21

Что будет выведено на экран?
```
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
x[[1,2,1]] += 1
print(x)
```

In [388]:
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
# x[[1,2,1]] += 1
# print(x)

[1 2 2 3 4]


In [389]:
tmp = x[[1,2,1]]
print(tmp) # [2 2 2]
tmp = tmp + 1 # [3 3 3]
print(tmp)
x[[1,2,1]] = tmp #[3 3 3] -> 1 3 3 3 4
print(x)

[2 2 2]
[3 3 3]
[1 3 3 3 4]


In [351]:
x[[0, 0, 1]] = range(3) # [0, 0, 1] := [0, 1, 2]

array([1, 3, 3, 3, 4])

# 22

Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. 

Какой из способов работает быстрее и почему?

In [150]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
%%timeit
a.ravel()

142 ns ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [166]:
(%%timeit
a.flatten())

551 ns ± 0.817 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [149]:
%%timeit
a.reshape(-1)

219 ns ± 23 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [2]:
a = np.arange(100).reshape(10,10)
b = a.reshape(-1) # view
c = a.ravel(order='F') # copy
print(np.shares_memory(a, b))
print(np.shares_memory(a, c))

True
False


In [185]:
a = np.arange(100).reshape(10,10)

b = a.reshape(-1)
c = a.T.ravel(order='K')
print(np.shares_memory(a, b))
print(np.shares_memory(a, c))
print(b)
print(c)

True
True
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [214]:
a = np.arange(10).reshape(2,5)
b = a[(0,1)]
print(type(b))
print(b)
np.shares_memory(b, a)

<class 'numpy.int64'>
1


False

In [253]:
a = np.arange(12).reshape(2,6)
b = a[:, ::2]
print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4]
 [ 6  8 10]]


In [254]:
b.reshape(-1).flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [247]:
a.ravel().flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# 23

1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [297]:
a = np.random.randint(10, size=10).astype(float)
print(a)
a[np.where(a == a.max())[0]] = a.mean()
print(a)

[2. 6. 8. 9. 4. 7. 9. 0. 8. 1.]
[2.  6.  8.  5.4 4.  7.  5.4 0.  8.  1. ]


# 24

1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [354]:
a = np.random.randint(10, 100, size=(6,6))
print(f'a array: \n{a}')
sum_ = a.sum(axis=1)
min_ = a.min(axis=0)
print(f'min value for each column {min_}')
print(f'sum for each row \n{sum_}')
b = sum_ / min_
print(f'result: \n{b}')

a array: 
[[30 33 34 51 63 91]
 [66 81 30 53 26 32]
 [69 30 20 53 63 99]
 [39 51 96 19 44 59]
 [55 70 99 13 14 50]
 [66 50 24 31 28 10]]
min value for each column [30 30 20 13 14 10]
sum for each row 
[302 288 334 308 301 209]
result: 
[10.06666667  9.6        16.7        23.69230769 21.5        20.9       ]


# 25

1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [ ]:
a = np.random.randint(5, 10, size=10)
print(a)
np.interp(a, (a.min(), a.max()), (-1, 2))

In [ ]:
min_ = -1
max_ = 2

a_min = a.min()
a_max = a.max()

scale = (max_ - min_) / (a_max - a_min) 
(a-a_min)*scale + min_

# 26

Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [237]:
a = np.array([[1, 7, 1, 0], [4, 2, np.nan, 4], [-1, np.nan, 2, 3], [np.nan, -1, -2, np.nan]])
print(a)
np.where(np.isnan(a), np.nanmean(a, axis=0), a)

[[ 1.  7.  1.  0.]
 [ 4.  2. nan  4.]
 [-1. nan  2.  3.]
 [nan -1. -2. nan]]


array([[ 1.        ,  7.        ,  1.        ,  0.        ],
       [ 4.        ,  2.        ,  0.33333333,  4.        ],
       [-1.        ,  2.66666667,  2.        ,  3.        ],
       [ 1.33333333, -1.        , -2.        ,  2.33333333]])

# 27

Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [250]:
a = np.array([[1, 0, 1, 0], [4, 0, 0, 0], [0, 0, 2, 0], [-8, 0, -2, 0]])
print(a)
print(~(a.any(axis=0)).all())

[[ 1  0  1  0]
 [ 4  0  0  0]
 [ 0  0  2  0]
 [-8  0 -2  0]]
True


# 28

1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [254]:
a = np.random.randint(9, size=(3,4,3,4))
a

array([[[[2, 3, 3, 1],
         [8, 7, 1, 6],
         [1, 0, 0, 2]],

        [[3, 4, 4, 7],
         [3, 2, 8, 3],
         [6, 3, 0, 8]],

        [[3, 2, 1, 0],
         [3, 1, 4, 1],
         [6, 8, 3, 3]],

        [[6, 4, 4, 4],
         [7, 7, 2, 5],
         [4, 0, 3, 0]]],


       [[[3, 8, 5, 3],
         [2, 5, 5, 8],
         [6, 4, 4, 4]],

        [[3, 7, 1, 8],
         [2, 8, 5, 5],
         [2, 8, 2, 4]],

        [[8, 4, 2, 0],
         [1, 2, 8, 2],
         [2, 7, 6, 7]],

        [[7, 0, 2, 5],
         [0, 3, 6, 8],
         [8, 7, 8, 2]]],


       [[[0, 8, 3, 4],
         [3, 8, 8, 4],
         [1, 8, 7, 4]],

        [[7, 6, 7, 6],
         [3, 5, 3, 8],
         [2, 7, 3, 7]],

        [[3, 2, 7, 1],
         [2, 2, 5, 1],
         [8, 4, 6, 3]],

        [[6, 2, 6, 5],
         [7, 2, 7, 3],
         [8, 1, 3, 6]]]])

In [257]:
print(a.sum(axis=(2,3), keepdims=True))

[[[[34]]

  [[51]]

  [[35]]

  [[46]]]


 [[[57]]

  [[55]]

  [[49]]

  [[56]]]


 [[[58]]

  [[64]]

  [[44]]

  [[56]]]]


# 29

1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [364]:
a = np.arange(10)
b = np.arange(10, 20)

c = np.zeros(a.shape[0], dtype=np.int8)
c[::2] = 1

np.where(c, a, b)

array([ 0, 11,  2, 13,  4, 15,  6, 17,  8, 19])

# 30

На примере массива 
```
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
```
вычислите долю пропущенных значений

In [365]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.isnan(x).mean()

0.375

# 31

На примере массива 
```
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
```
составьте массив из уникальных значений массива без учета nan

In [3]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.unique(x[~np.isnan(x)])

array([1., 2., 3., 5.])

# 32

На примере массива 
```
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
```
найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [12]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = np.zeros(x.shape[0], dtype=bool)
mask[1:] = x[:-1] == 0
#x[mask].max()
x[mask].max()

5

In [3]:
np.array([]).max()

ValueError: zero-size array to reduction operation maximum which has no identity

# 33

Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [240]:
a = np.arange(-5, 5, dtype=float)
b = np.arange(-3, 7, dtype=float)
print(a)
print(b)
np.divide(a, b, where=b!=0)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]
[-3. -2. -1.  0.  1.  2.  3.  4.  5.  6.]


array([ 1.66666667,  2.        ,  3.        ,  0.        , -1.        ,
        0.        ,  0.33333333,  0.5       ,  0.6       ,  0.66666667])

In [244]:
b = np.zeros(10, dtype=np.int16)
np.divide(a, b, where=b!=0)

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

# 34

Пусть заданы два массива 
```
x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]).
```
Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [23]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at(x, i, 1)
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# 35

По заданному массиву 
```
y = np.bincount([0, 0, 3, 8, 10, 10, 11])
```
постройте массив x такой, чтобы np.bincount(x) = y

In [190]:
y = np.bincount([0, 0, 3, 8, 10, 10, 11])
x = np.repeat(np.arange(y.shape[0]), y)
x

array([ 0,  0,  3,  8, 10, 10, 11])

# 36

Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива 

```x = np.array([0,1,2,0,6,6,7,4,5,4]).```

In [182]:
x = np.array([0,1,2,0,6,6,7,4,5,4])
bincount = np.bincount(x)
np.where(bincount == np.max(bincount))[0]

array([0, 4, 6])

In [7]:
np.bincount(np.array([-3, 0, 5, 10]))

ValueError: 'list' argument must have no negative elements

# 37

Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива 
```
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]]),
```
в результате должен получиться список 
```[array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])].```

In [8]:
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5], [1, 5]])
unique, indices = np.unique(x[:, 0], return_index=True)
np.split(x, indices[1:])

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5],
        [1, 5]])]

In [14]:
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5], [1, 5]])
x = x[x[:, 0].argsort()]
indices = np.where(x[:-1, 0] != x[1:, 0])[0] + 1
np.split(x, indices)
#indices

[array([[1, 2],
        [1, 3],
        [1, 5]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

# 38

"По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, сожержащих элементы из полуинтервалов

```[i * 10, (i+1) * 10), i = 0, 1, 2, …```

Решите задачу на примере массива

```x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20]),``` 
в результате должен получиться список 
```
[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])].
```

In [198]:
%%timeit
#x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20, 80])
x = np.random.randint(0, 100, size=10000)
x.sort()

bins = x[-1] // 10 + 1
intervals = np.arange(10, bins*10, step=10)

indices = np.searchsorted(x, intervals, side='left')
result = np.split(x, indices)

353 µs ± 774 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [239]:
%%timeit
#x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20, 80])
x = np.random.randint(0, 100, size=10000)
bins = set(x // 10)
result = [x[np.where(x//10 == bin_)] for bin_ in bins]
#result

999 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [253]:
%%timeit
#x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20, 80])
x = np.random.randint(0, 100, size=10000)
bins = np.array(list(set(x // 10))).reshape(-1, 1)

mask = x//10 == bins
result = [x[mask[i]] for i in range(mask.shape[0])]
#result

972 µs ± 816 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [200]:
%%timeit
#x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20, 80])
x = np.random.randint(0, 100, size=10000)
intervals = {}
for elem in x:
    try:
        intervals[elem//10].append(elem)
    except KeyError:
        intervals[elem//10] = [elem]
        
result = [np.array(intervals[key]) for key in intervals.keys()]
#result

2.39 ms ± 2.54 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 39

Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?

In [15]:
a = np.arange(0, 6).reshape(2, 3)
b = np.arange(6, 15).reshape(3, 3)

In [16]:
#%%timeit
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
#%%timeit
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
#%%timeit
np.stack((a,b))

ValueError: all input arrays must have the same shape

# 40

Для двух одномерных массивов x = np.arange(3) и y = np.arange(5) постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

In [102]:
x = np.arange(3)
y = np.arange(5)

np.dstack(np.meshgrid(x, y)).reshape(-1, 2)

array([[0, 0],
       [1, 0],
       [2, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4]])

# 41

По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
Решите задачу на примере массивов 
```
x = np.array([1,2,3,4]) и y = np.array([5,6,7,8]).
```

In [256]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

print(np.concatenate((x[:,np.newaxis], y[:,np.newaxis]), axis=1))
print(np.dstack((x,y)))
print(np.dstack((x,y)).squeeze())

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [260]:
np.column_stack((x, y))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# 42

По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив полностью заполненный нулями.
Решите задачу для списка 
```
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])].
```

In [262]:
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]

ar_shape = l[0].shape

a = np.zeros((2 * len(l) - 1, *ar_shape))
a[::2] = np.stack(l)
a

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 9., 10.],
        [11., 12.]]])

# 43

Преобразуйте одномерный массив 
```x = np.array([3,7,2,5,0,9,8,2,4,5])```
в двумерный массив, первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

In [268]:
x = np.array([3,7,2,5,0,9,8,2,4,5], dtype=np.int16)
b = np.lib.stride_tricks.as_strided(x, (x.shape[0] - (5 - 1), 5), (x.itemsize, x.itemsize))
b

array([[3, 7, 2, 5, 0],
       [7, 2, 5, 0, 9],
       [2, 5, 0, 9, 8],
       [5, 0, 9, 8, 2],
       [0, 9, 8, 2, 4],
       [9, 8, 2, 4, 5]], dtype=int16)

In [267]:
b.itemsize

2

# 44

Для заданного двумерного массива постройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла. Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
Решите задачу на примере массива 
```x = np.arange(49).reshape(7,7).```

In [46]:
a = np.arange(8).reshape(2,2,2)
a.strides

(32, 16, 8)

In [270]:
x = np.arange(49).reshape(7,7)
print(x)

shape_x = (x.shape[0] // 3) * 3
shape_y = (x.shape[1] // 3) * 3

n_blocks = (shape_x // 3) * (shape_y // 3)

x_stride = x.itemsize 
y_stride = x.itemsize * x.shape[1]

x_4d = np.lib.stride_tricks.as_strided(
    x, 
    (x.shape[0]//3, x.shape[1]//3, 3, 3), 
    (x.itemsize * 3 * x.shape[1] ,x.itemsize * 3 ,x.itemsize * x.shape[1], x.itemsize)
)
x_3d = x_4d.reshape(-1, 3, 3)
x_3d
# x_3d = np.lib.stride_tricks.sliding_window_view(x_new, (3, 3))[::3, ::3].reshape(n_blocks, 3, 3)
# x_3d

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


array([[[ 0,  1,  2],
        [ 7,  8,  9],
        [14, 15, 16]],

       [[ 3,  4,  5],
        [10, 11, 12],
        [17, 18, 19]],

       [[21, 22, 23],
        [28, 29, 30],
        [35, 36, 37]],

       [[24, 25, 26],
        [31, 32, 33],
        [38, 39, 40]]])

# 45

Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0.

In [100]:
a = np.zeros(19, dtype=np.int64)
a = np.concatenate((np.array([100]), a))

mean = a.mean()
sigma = a.std()

masked_out = ma.masked_outside(a, mean-3*sigma, mean+3*sigma, )
masked_out

masked_array(data=[--, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                   0, 0],
             mask=[ True, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999)

# 46

"Удалите из двумерного массива столбцы, ко всем элементам которых применена маска.
Решите задачу на примере массива 
```
x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]]).
```


In [264]:
x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])
print(x.mask.all(axis=0))
x.mask = x.mask.all(axis=0)
print(x.mask)
#x = ma.compress_cols(x)
#x
x[x.mask] = 0
x

[False  True False]
[[False  True False]
 [False  True False]]


masked_array(
  data=[[1, 0, 3],
        [4, 0, 6]],
  mask=[[False, False, False],
        [False, False, False]],
  fill_value=999999)

In [262]:
x.mask

array([[False, False, False],
       [False, False, False]])

# 47

"Примените маску к минимальному и максимальному элементу каждой строки двумерного массива.
Решите задачу на примере массива 
```
x = np.arange(25).reshape(5, 5).
```

In [266]:
x = np.arange(25).reshape(5, 5)
print(x)
#condition = np.bitwise_or(x == x.max(axis=1, keepdims=1), x == x.min(axis=1, keepdims=1))
condition = (x == x.max(axis=1, keepdims=1)) | (x == x.min(axis=1, keepdims=1))

m = ma.masked_where(condition, x)
m

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


masked_array(
  data=[[--, 1, 2, 3, --],
        [--, 6, 7, 8, --],
        [--, 11, 12, 13, --],
        [--, 16, 17, 18, --],
        [--, 21, 22, 23, --]],
  mask=[[ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True]],
  fill_value=999999)

# 48

Примените медианный фильтр с нечетной шириной окна k к заданному одномерному массиву a: i-е значение результирующего массива вычисляется как медиана подмассива 
```
a[i - (k-1)/2: i - (k-1)/2 + 1].
```
В случае если границы окна выходят за границы массива, дополните исходный массив требуемым числом элементов a[0] или a[-1] с нужной стороны.
Решите задачу на примере массива 
```
a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
```
и ширины окна k = 5."

In [258]:
%%timeit
#a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
a = np.random.randint(-100, 100, size=1000, dtype=np.int64)
k = 5
shape = a.shape[0]

padded_a = np.hstack((np.tile(a[0], (k-1)//2), a, np.tile(a[-1], (k-1)//2)))

#print(padded_a)

median_filter = np.empty(shape)

for i in range(len(a)):
    median_filter[i] = np.median(padded_a[i:i+k])

17.3 ms ± 1.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [257]:
%%timeit
#a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
a = np.random.randint(-100, 100, size=1000, dtype=np.int64)
k = 5
shape = a.shape[0]
itemsize = a.itemsize

padded_a = np.hstack((np.tile(a[0], (k-1)//2), a, np.tile(a[-1], (k-1)//2)))

#print(padded_a)

result = np.median(np.lib.stride_tricks.as_strided(padded_a, (shape, k), (itemsize, itemsize)), axis=1)

142 µs ± 211 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# 49

"По заданному массиву a размера Nx2 постройте одномерный массив длины N, i-й элемент которого - сумма i-го элемента первого столбца массива a и элемента первого столбца, индекс которого содержится в i-й строке второго столбца. В случае, если во втором столбце массива a содержится индекс, выходящий за границы, к элементу первого столбца ничего не прибавляйте.
Решите задачу на примере массива 
```
a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]]).
```

In [162]:
a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])
out = np.zeros(a.shape[0])

for i in range(a.shape[0]):
    if a[i, 1] < a.shape[0] and a[i, 1] >= 0:
        out[i] = a[i, 0] + a[a[i, 1], 0]
    else:
        out[i] = a[i, 0]
out

array([13.,  6., 16.,  9., 12.])

# 50

"По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях.
Решите задачу на примере массива 
```
a = np.arange(16).reshape(4, 4)
```
в результате должен получиться словарь
```
{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}.
```

In [178]:
a = np.arange(16).reshape(4, 4)
print(a)
a = np.fliplr(a)
print(a)

diag_dict = {}

for k in range(2 * a.shape[0] - 1):
    diag_dict[k] = np.diag(a, a.shape[0] - 1 - k).tolist()
diag_dict

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}

# Numpy task from starters

In [2]:
!pip install --upgrade numexpr

In [3]:
import os
os.environ['NUMEXPR_MAX_THREADS'] = '16'
os.environ['NUMEXPR_NUM_THREADS'] = '8'
import numexpr as ne

## 1

In [2]:
X = 100
Y = 100
Z = 30
N = 20

A = np.random.randint(-100, 100, size=(X, Y, Z))
B = np.random.randint(-100, 100, size=(N, Z))

### Baseline

In [3]:
def corr(first, second):
    return ((first*second).mean() - first.mean() * second.mean()) / (first.std()*second.std())

In [4]:
def corr_baseline(A, B):
    X,Y,Z = A.shape
    N, Z = B.shape
    corr_matrix = np.empty((X, Y))

    for ij in np.ndindex(A.shape[:2]):
        A_trace = A[ij]
        sum_ = 0
        for B_trace in B:
            sum_ += corr(A_trace, B_trace)
        corr_matrix[ij] = sum_/B.shape[0]
    return corr_matrix

### Solution

In [5]:
from Task_from_starters import first_task

baseline_result = corr_baseline(A, B)
my_result = first_task(A, B)

(baseline_result.round(10) == my_result.round(10)).all()

True

## 2

In [6]:
X = 1000
Y = 1000
Z = 30
K = 3

A = np.random.randint(-100, 100, size=(X, Y, Z))

### Baseline

In [9]:
def create_blocks(A, K):
    """
    Creates K x K x Z blocks from original array, and reshapes it into K^2 x Z blocks

    Returns:
        array of shape: (n_blocks, K^2, Z)
    """

    itemsize = A.itemsize
    X, Y, Z = A.shape

    BATCH_SIZE = (K, K, Z)
    x_blocks = A.shape[0] - (K - 1)
    y_blocks = A.shape[1] - (K - 1)
    n_blocks = x_blocks * y_blocks

    blocks = np.lib.stride_tricks.as_strided(
        A,
        shape = (n_blocks, K, K, Z),
        strides = (
            itemsize*Z,
            itemsize*Z*Y,
            itemsize*Z,
            itemsize
        )
    )
    # flattening kxkxz traces into k^2xz so that central trace will be in center of resulting array
    blocks = blocks.reshape(n_blocks, K*K, Z)
    return blocks, n_blocks, x_blocks, y_blocks

In [10]:
def mean_corr(A, K):
    X, Y, Z = A.shape
    
    blocks, n_blocks, x_blocks, y_blocks = create_blocks(A, K)
    blocks = blocks.reshape(n_blocks, K*K, Z)
    central_tr = blocks[:, blocks.shape[1]//2, :].reshape(n_blocks, 1, Z)

    result = ((blocks * central_tr).mean(axis=2) - central_tr.mean(axis=2) * blocks.mean(axis=2)) / (central_tr.std(axis=2) * blocks.std(axis=2))

    result = (result.sum(axis=1) - 1) / (K**2 - 1)
    return result.reshape((x_blocks, y_blocks))

### Solution

In [11]:
from Task_from_starters import second_task

baseline_result = mean_corr(A, K)
my_result = second_task(A, K)

(baseline_result == my_result).all()

True